spring:
  profiles:
    active: dev


---

server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.funyims.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/DB01?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #数据源

#EUREKA 配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://funyims01:7001/eureka/,http://funyism02:7002/eureka/,http://funyims03:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改默认描述信息

#info配置

info:
  app.name: funyims-springcloud
  company.name: funyims.com

---


server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.funyims.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/DB02?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #数据源

#EUREKA 配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://funyims01:7001/eureka/,http://funyism02:7002/eureka/,http://funyims03:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改默认描述信息

#info配置

info:
  app.name: funyims-springcloud
  company.name: funyims.com

