spring:
  profiles:
    active: dev


---

server:
  port: 7001

#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
  

#Eureka配置
eureka:
  instance:
    hostname: funyims01 #Eureka server实例子名称
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false #如果为false 表示自己是注册中心
    service-url: #监控页面
      #单机
      #集群（关联）
      defaultZone: http://funyims02:7002/eureka/,http://funyims03:7003/eureka/

---


server:
  port: 7001

#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
  

#Eureka配置
eureka:
  instance:
    hostname: funyims01 #Eureka server实例子名称
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false #如果为false 表示自己是注册中心
    service-url: #监控页面
      #单机
      #集群（关联）
      defaultZone: http://funyims02:7002/eureka/,http://funyims03:7003/eureka/

